Feature 18
Doc-Docker/APISubiter pull request #37
Opened 2022-09-09 22:53 UTC by Antonio-Zago

Pasta do front end sem o bug

2022-09-12 00:13 UTC, VictorCavichioli requested changes
Sua change está boa em quesito de código, apenas falta lapidar algumas arestas, bom trabalho, use meus comentários como um "Norte", não é necessário concordar com tudo, esse é um espaço de discussão, se tiver ideias melhores, explique e defenda seu ponto de vista, o intuito no final é sempre evolução de ambos.

2022-09-12 00:13 UTC, VictorCavichioli commented on APISubiterFrontend/src/services/config.js
> +
Remova linha vazia nos imports

2022-09-12 00:13 UTC, VictorCavichioli commented on APISubiterFrontend/src/views/CadastroEquipamentoView.vue
> +  <script>
Não sou especialista, mas acredito que dê para extrair esse script em um arquivo de serviço, né? E no lucar que tem o script você colocar a referência de onde está o script no projeto, seguindo as boas práticas de OO e também permanecendo mais organizado, já que já temos uma pasta de services, penso que talvez possa ser uma pasta de "exports" ou algo relacionado ao que o método está fazendo

2022-09-12 00:13 UTC, VictorCavichioli commented on APISubiterFrontend/src/views/CadastroServicoInstalacaoView.vue
> +<script>
Mesmo acima

2022-09-12 00:13 UTC, VictorCavichioli commented on APISubiterFrontend/src/views/HomeView.vue
> +
Linha vazia

2022-09-12 00:13 UTC, VictorCavichioli commented on APISubiterFrontend/src/views/ListagemEquipamentoView.vue
> +    <!---->
Comentário sem comentário, para que?

2022-09-12 00:13 UTC, VictorCavichioli commented on APISubiterFrontend/src/views/ListagemEquipamentoView.vue
> +
Linha vazia

2022-09-12 00:13 UTC, VictorCavichioli commented on APISubiterFrontend/src/views/ListagemEquipamentoView.vue
> +              >
Acho que esse sinal ">" poderia estar no fechamento do label, não acha?

2022-09-12 00:13 UTC, VictorCavichioli commented on APISubiterFrontend/src/views/ListagemEquipamentoView.vue
> +              >
Same above

2022-09-12 00:13 UTC, VictorCavichioli commented on APISubiterFrontend/src/views/ListagemEquipamentoView.vue
> +  <script>
Mesmo que disse anteriormente

2022-09-12 00:13 UTC, VictorCavichioli commented on APISubiterFrontend/src/views/ListagemServicosView.vue
> +  <!---->
Novamente

2022-09-12 00:13 UTC, VictorCavichioli commented on APISubiterFrontend/src/views/ListagemServicosView.vue
> +            >
Utilize os comentários que fiz anteriormente para correr pelo arquivo e concertar todas as ocorrências de linhas vazias, scripts e sinais de label

2022-09-13 00:52 UTC, ZaionKun approved these changes

2022-09-13 00:52 UTC, merged